#!/bin/bash

set -e

echo "LIQUIBASE_DRIVER=$LIQUIBASE_DRIVER"
echo "LIQUIBASE_URL=$LIQUIBASE_URL"
echo "LIQUIBASE_CHANGELOG=$LIQUIBASE_CHANGELOG"
echo "LIQUIBASE_USERNAME=$LIQUIBASE_USERNAME"
echo "LIQUIBASE_PASSWORD=$LIQUIBASE_PASSWORD"

/opt/jboss/liquibase --driver=$LIQUIBASE_DRIVER --changeLogFile=/opt/jboss/data/$LIQUIBASE_CHANGELOG --url=$LIQUIBASE_URL --username=$LIQUIBASE_USERNAME --password=$LIQUIBASE_PASSWORD $1 

